version: '3.9'

services:
  db:
    image: mariadb:10.5.8
    container_name: mariadb1058
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbfile:/var/lib/mysql
    # command: ''
    networks:
      - app

  wp:
    image: wordpress:5.7.0-php8.0-fpm
    container_name: wordpress-5.7.0-php8.0-fpm
    depends_on:
      - mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - www-html:/var/www/html
    networks:
      - app

  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - wp
    container_name: nginx-1.19.8-alpine
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=caugusta.42.fr
    ports:
      - "80:80"
    volumes:
      - www-html:/var/www/html
      - /Users/nikita/Desktop/Projects/Inception/srcs/requirements/nginx/tools/conf.d:/etc/nginx/conf.d/caugusta.42.fr.conf
    networks:
      - app

volumes:
  www-html:
  dbfile:

networks:
  app:
    driver: bridge
