version: '3.9'

services:
  db:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - /Users/nikita/data/db:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    # command: ''
    networks:
      - app

  wp:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - /Users/nikita/data/wp:/var/www/html
    depends_on:
      - db
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    networks:
      - app

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - /Users/nikita/data/wp:/var/www/html
    depends_on:
      - wp
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=caugusta.42.fr
    ports:
      - "443:443"
    networks:
      - app

volumes:
  wp:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      device: /Users/nikita/data/wp
      o: bind
      # device: /home/caugusta/data/wp
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      device: /Users/nikita/data/db
      o: bind
      # device: /home/caugusta/data/db

networks:
  app:
    driver: bridge
